name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # L'action se déclenche pour les push sur la branche main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout le code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Login au registre GitHub Packages
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Construire l'image Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/jokes-fetcher:latest .

      # 4. Pousser l'image sur GitHub Packages
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/jokes-fetcher:latest
